from typing import Protocol, Dict, List, Optional, Tuple

Bible = Dict[str, Dict[str, List[str]]]

class BibleRepository(Protocol):
    def get_books(self) -> List[str]: ...
    def get_chapter_count(self, book: str) -> int: ...
    def get_verse_count(self, book: str, chapter: int) -> int: ...
    def find_text(self, book: str, chapter: int, verse: int) -> str: ...
"""
# Step 1: Define BibleRepository interface for infrastructure adapters
"""
